name: test

on:
  - push
  - pull_request

jobs:
  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "commit message doesn't contain '[skip ci]'"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - '1.4.8'
          - '1.6.12'
          - 'devel'
    needs: before
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: nimble install -y
      - run: nimble test
      - run: nimble checkExamples

name: docs
on:
  push:
    branches:
      - master
env:
  nim-version: 'stable'
  nim-src: src/${{ github.event.repository.name }}.nim
  deploy-dir: .gh-pages
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim-version }}
      - run: nimble install -Y
      - run: nimble doc --index:on --project --git.url:https://github.com/${{ github.repository }} --git.commit:master  --out:${{ env.deploy-dir }} ${{ env.nim-src }}
      - name: "Copy to index.html"
        run: cp ${{ env.deploy-dir }}/${{ github.event.repository.name }}.html ${{ env.deploy-dir }}/index.html
      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.deploy-dir }}
